env: "local" # local, dev, prod
storage_path: "./storage/storage.db"
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s

database:
  type: "sqlite" # sqlite, postgres, mysql
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: "1h"
logging:
  level: "info" # debug, info, warn, error
  format: "json" # json, console
  output: "stderr" # stdout, stderr, file
auth:
  jwt_secret: "your-jwt-secret-key"
  token_expiry: "24h"
  